services:
  postgres:
    image: postgres:15-alpine
    container_name: final4-postgres
    environment:
      POSTGRES_DB: final4
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    entrypoint: ["sh", "-c", "echo 'CREATE SCHEMA IF NOT EXISTS world;' > /docker-entrypoint-initdb.d/init.sql && exec docker-entrypoint.sh postgres"]
    restart: always

  redis:
    image: redis:7-alpine
    container_name: final4-redis
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    container_name: final4-javarush
    depends_on:
      - postgres
      - redis
    environment:
      - DB_NAME=final4
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=
      - DB_PASSWORD=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: on-failure